name: env-ml
channels:
  - conda-forge
dependencies:
  # ML & stats
  - python-blosc2
  - scikit-learn
  - emcee
  - lmfit
  - mpmath
  - xtensor<=0.25.0
  - xtensor-blas

  # Visualization
  - matplotlib
  - seaborn
  - bokeh
  - panel
  - holoviews
  - hvplot
  - datashader
  - corner
  - cmcrameri
  - imageio
  - python-graphviz
  - tk
